In [1]:
import pandas as pd

In [22]:
df_098 = pd.read_csv ('alon_inputs .csv', header=None)

In [23]:
df_098.columns

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999],
           dtype='int64', length=2000)

In [24]:
df_098 [df_098.columns[50:60+1] ]

50       51       52       53       54       55       56       57  \
0   2344.61  2344.61  2344.61   845.02  1528.79  1185.71   728.46  1148.16   
1   1559.28  1559.28  1559.28  1166.20  2893.84  2249.17  1451.45  2004.15   
2   1109.33  1109.33  1109.33   469.98   933.44   349.67   725.45   631.54   
3   1651.35  1651.35  1651.35   505.06  2144.33   986.54  1225.80   676.17   
4   1293.48  1293.48  1293.48  1632.69   814.50  1491.30  1247.14  1032.97   
..      ...      ...      ...      ...      ...      ...      ...      ...   
57  1071.37  1071.37  1071.37   895.53  1747.30   546.45   595.66  1059.00   
58  3649.71  3649.71  3649.71  2807.01  3537.35  1863.23  2855.62  2120.93   
59  1488.15  1488.15  1488.15  1350.04  1970.67  1361.16  1243.83  1737.28   
60  1509.07  1509.07  1509.07   999.24  1463.90  1874.45  1947.59  1169.51   
61  1417.22  1417.22  1417.22  1186.37  2237.32  2271.03  1748.54  1889.00   

         58       59       60  
0   3684.62  1397.47   849.18  
1   3002.40  1700.52   850.12  
2    565.65   660.25   349.90  
3   1092.15  1050.19   498.44  
4    399.98  1421.37   961.88  
..      ...      ...      ...  
57  1617.58   622.62   358.53  
58  1416.57  2796.62  1153.38  
59  2688.17   901.82   621.57  
60   974.20  1329.86   671.23  
61  2502.80  2080.22  1277.21  

[62 rows x 11 columns]

In [25]:
print( df_098[df_098.columns[50:60+1] ].mean() )

50    2118.013065
51    2118.013065
52    2118.013065
53    1523.162742
54    1994.882097
55    1852.319839
56    1811.608226
57    1844.129194
58    1716.091935
59    2050.632419
60    1114.501452
dtype: float64


In [26]:
df_098 [ filter ( lambda x:x%2==1 , df_098.columns [1:500+1] )].median ()

1      4738.280
3      3451.500
5      4416.620
7      2844.960
9      3823.020
         ...   
491     242.785
493     398.190
495     334.705
497     339.725
499     483.385
Length: 250, dtype: float64

In [27]:
df_098[[0,1,2]]

0        1        2
0   8589.42  5468.24  4263.41
1   9164.25  6719.53  4883.45
2   3825.71  6970.36  5369.97
3   6246.45  7823.53  5955.84
4   3230.33  3694.45  3400.74
..      ...      ...      ...
57  4972.17  4173.92  3668.53
58  9112.37  6824.49  5982.85
59  6730.63  3472.13  2559.46
60  6234.62  4005.30  3093.68
61  7472.01  3653.93  2728.22

[62 rows x 3 columns]

In [28]:
def bagi1000(x):
    return x/1000

def bulatkan(x):
    return round (x,2)

#df = df.aplly (lambda x:round(x?1000,2))
df_098= df_098.apply(lambda x:round x:round (x/1000,2) )
df_098= df_098.apply(bagi1000)
df_098= df_098.apply(bulatkan)
df_098

SyntaxError: invalid syntax (3010034171.py, line 8)

In [32]:
df2_098 = df_098.drop (df_098.columns[1:500++1], axis=1)

In [33]:
df2_098.head()

0       501     502     503     504     505     506     507     508   \
0  8589.42  128.59  438.03  315.52  322.91  511.06  235.23  206.00  407.55   
1  9164.25  135.79  425.41  379.99  391.08  767.34  335.13  255.16  533.77   
2  3825.71   89.44  264.73  166.97  205.51  915.70  132.73  140.16  152.50   
3  6246.45   96.64  231.29  529.35  156.63  952.50  148.33  164.17  198.60   
4  3230.33  243.89  244.68  229.46  188.08  283.84  242.08  186.30  222.38   

     509   ...    1990   1991    1992    1993   1994    1995    1996    1997  \
0  207.67  ...   99.11  67.56  259.91  138.90  88.23   39.67   67.83   75.68   
1  175.97  ...  126.79  92.24   96.28  150.59  82.24   85.03  152.20  186.57   
2   59.35  ...  151.88  82.72   31.10  193.92  76.97  224.62   31.23   42.66   
3   93.15  ...  152.60  41.68    5.93  183.01  74.53   67.71   48.34   42.52   
4  157.84  ...  126.46  76.60  161.35   61.70  54.56  223.36   73.10   57.60   

    1998   1999  
0  83.52  28.70  
1  44.47  16.77  
2  16.09  15.16  
3  49.98  16.09  
4   7.49  31.81  

[5 rows x 1500 columns]

In [31]:
df_098[[ i for i in range(1, 501,2)]]

1        3         5        7        9        11       13       15   \
0   5468.24  4064.94   5282.33  2773.42  4607.68  1522.65  1181.63  3139.40   
1   6719.53  3718.16   5569.91  2793.39  4802.25  1792.18  3630.38  5745.40   
2   6970.36  4705.65   1572.17  1472.26  2786.58  1487.67   855.46  3251.11   
3   7823.53  3975.56   2130.54  1714.63  4989.41  1298.73  1789.67  3496.15   
4   3694.45  3463.59   2922.78  2948.58  3109.41  2557.78  2285.31  3056.73   
..      ...      ...       ...      ...      ...      ...      ...      ...   
57  4173.92  1567.56   3466.81  1535.76  3519.60  1291.82   937.24  1591.60   
58  6824.49  3147.04  11222.68  4299.50  5888.55  3105.43  3450.61  4989.69   
59  3472.13  2624.69   4372.79  1026.48  3243.17  1272.51  2715.22  4483.50   
60  4005.30  3183.09   3940.85  1406.65  2177.32  1329.44  1270.17  2431.40   
61  3653.93  3494.48   5791.61  2150.96  2685.30  1655.31  3764.36  3681.35   

        17       19   ...     481     483     485      487     489     491  \
0   1306.90  1900.36  ...  166.17  392.92  376.94   341.41  255.01  148.53   
1   2036.28  2490.87  ...  358.50  490.24  496.67   401.08  347.14  240.34   
2   1618.65  1006.21  ...   61.40  269.30  440.31   304.09   60.77  139.56   
3   1597.28  1139.63  ...  169.61  549.16  224.64   472.72  137.25  182.44   
4   2162.55  2705.68  ...  385.38  242.79  400.19   251.42  241.98  175.27   
..      ...      ...  ...     ...     ...     ...      ...     ...     ...   
57   848.97  1651.60  ...  204.40  296.33  105.25   234.16  178.49  146.24   
58  3717.11  3591.00  ...  705.27  599.41  179.59  1766.49  874.90   93.85   
59  1391.83  2214.79  ...  393.09  566.33  280.22   842.11  304.20  323.85   
60  1163.01  1996.96  ...  394.68  314.45  126.34   264.01  164.68  328.36   
61  2148.93  1993.01  ...  518.99  409.16  185.21   361.66  300.27  163.66   

       493     495     497      499  
0   494.07  381.67  339.00   204.80  
1   469.86  394.59  342.05   345.91  
2   176.26  195.52  543.09   136.57  
3   304.08  321.43  320.65   176.12  
4   197.91  157.78  583.00   381.57  
..     ...     ...     ...      ...  
57  222.90  409.33   89.38   617.29  
58  393.37  542.19   69.06  2126.69  
59  424.18  411.67  193.39   183.59  
60  274.59  285.02  101.49   515.08  
61  389.31  330.86  181.36   817.90  

[62 rows x 250 columns]

In [34]:
df2_098.to_csv('jurnal_SSD_modul1.csv')

In [35]:
s = pd.Series( range(-5,10+1) )
s.values

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
      dtype=int64)

In [36]:
import numpy as np

NIMS = np.random.choice( range(100,1000), 100 , replace=False)
NIMS

array([686, 330, 531, 825, 687, 838, 214, 379, 295, 596, 720, 133, 733,
       956, 737, 333, 123, 858, 248, 131, 628, 180, 752, 282, 201, 504,
       124, 708, 250, 160, 638, 334, 357, 466, 491, 514, 914, 477, 679,
       939, 313, 246, 210, 216, 371, 243, 630, 130, 450, 921, 646, 652,
       690, 392, 219, 281, 428, 291, 634, 386, 619, 932, 380, 875, 322,
       469, 363, 179, 580, 406, 473, 824, 552, 964, 263, 465, 771, 254,
       854, 235, 495, 343, 749, 894, 563, 141, 996, 224, 594, 946, 247,
       223, 747, 398, 529, 625, 492, 174, 806, 911])

In [37]:
Nilai_UTS = np.random.uniform(0,100,100)
Nilai_UTS

array([77.64054608, 45.6973739 ,  9.47992921,  0.96138313, 68.2118029 ,
       68.66698556,  1.94105502, 59.56651771, 20.41167429, 31.79968379,
       70.2293692 ,  3.53921389,  8.1234588 ,  4.6328524 , 54.39926224,
       20.62332185, 69.75654298, 54.53692484, 76.60318093, 79.96820109,
       50.62015761, 94.73007212, 53.83913429, 81.4134443 , 61.06031693,
       28.61667693, 78.66020063, 87.83911324,  0.86619335, 26.53268979,
       61.13345056, 38.93913981, 54.47440059, 58.06408157, 84.95193844,
       46.38866077, 26.80845084, 61.23016352, 32.10753718, 92.04375914,
       95.54926393, 51.47754179, 77.19543428, 44.49435626, 60.88379033,
        1.02691686, 31.99137192, 20.90694661, 12.6767869 , 69.16565546,
       51.84560641, 60.9773871 , 12.75007774, 37.68531711, 11.59014921,
       53.65915104, 45.43620152, 82.39298687, 75.05802749, 12.87582763,
       65.22764439, 27.86321795,  7.79620176, 22.24447129,  3.31994885,
       16.03299021, 70.59389772, 24.94983819, 81.97024546,  1.33

In [38]:
Nilai_UTS = np.round(Nilai_UTS,2)
Nilai_UTS

array([77.64, 45.7 ,  9.48,  0.96, 68.21, 68.67,  1.94, 59.57, 20.41,
       31.8 , 70.23,  3.54,  8.12,  4.63, 54.4 , 20.62, 69.76, 54.54,
       76.6 , 79.97, 50.62, 94.73, 53.84, 81.41, 61.06, 28.62, 78.66,
       87.84,  0.87, 26.53, 61.13, 38.94, 54.47, 58.06, 84.95, 46.39,
       26.81, 61.23, 32.11, 92.04, 95.55, 51.48, 77.2 , 44.49, 60.88,
        1.03, 31.99, 20.91, 12.68, 69.17, 51.85, 60.98, 12.75, 37.69,
       11.59, 53.66, 45.44, 82.39, 75.06, 12.88, 65.23, 27.86,  7.8 ,
       22.24,  3.32, 16.03, 70.59, 24.95, 81.97,  1.34, 24.17, 71.45,
       83.08,  7.95, 37.24,  8.28, 54.88, 45.09,  1.92, 32.9 , 24.1 ,
       21.07, 24.36,  3.68,  7.62,  3.51, 95.48, 78.5 , 48.81, 16.73,
       98.25, 58.47, 85.03, 26.75, 66.82, 41.79, 11.74, 21.8 , 72.49,
       59.15])

In [39]:
df_098 = pd.DataFrame({ 'NIM':NIMS, 'NILAI':Nilai_UTS })
df_098

NIM  NILAI
0   686  77.64
1   330  45.70
2   531   9.48
3   825   0.96
4   687  68.21
..  ...    ...
95  625  41.79
96  492  11.74
97  174  21.80
98  806  72.49
99  911  59.15

[100 rows x 2 columns]

In [40]:
df_098['NILAI'].describe()

count    100.000000
mean      44.112100
std       28.742283
min        0.870000
25%       20.567500
50%       45.570000
75%       68.795000
max       98.250000
Name: NILAI, dtype: float64

In [41]:
df_098[ df_098['NILAI'] > 50]

NIM  NILAI
0   686  77.64
4   687  68.21
5   838  68.67
7   379  59.57
10  720  70.23
14  737  54.40
16  123  69.76
17  858  54.54
18  248  76.60
19  131  79.97
20  628  50.62
21  180  94.73
22  752  53.84
23  282  81.41
24  201  61.06
26  124  78.66
27  708  87.84
30  638  61.13
32  357  54.47
33  466  58.06
34  491  84.95
37  477  61.23
39  939  92.04
40  313  95.55
41  246  51.48
42  210  77.20
44  371  60.88
49  921  69.17
50  646  51.85
51  652  60.98
55  281  53.66
57  291  82.39
58  634  75.06
60  619  65.23
66  363  70.59
68  580  81.97
71  824  71.45
72  552  83.08
76  771  54.88
86  996  95.48
87  224  78.50
90  247  98.25
91  223  58.47
92  747  85.03
94  529  66.82
98  806  72.49
99  911  59.15

In [42]:
df2_098 = df_098[ df_098['NIM']%2==1]

In [43]:
df2_098['NIM'].values

array([531, 825, 687, 379, 295, 133, 733, 737, 333, 123, 131, 201, 357,
       491, 477, 679, 939, 313, 371, 243, 921, 219, 281, 291, 619, 875,
       469, 363, 179, 473, 263, 465, 771, 235, 495, 343, 749, 563, 141,
       247, 223, 747, 529, 625, 911])

In [44]:
df2_098.sort_values(by='NIM')

NIM  NILAI
16  123  69.76
19  131  79.97
11  133   3.54
85  141   3.51
67  179  24.95
24  201  61.06
54  219  11.59
91  223  58.47
79  235  32.90
45  243   1.03
90  247  98.25
74  263  37.24
55  281  53.66
57  291  82.39
8   295  20.41
40  313  95.55
15  333  20.62
81  343  21.07
32  357  54.47
66  363  70.59
44  371  60.88
7   379  59.57
75  465   8.28
65  469  16.03
70  473  24.17
37  477  61.23
34  491  84.95
80  495  24.10
94  529  66.82
2   531   9.48
84  563   7.62
60  619  65.23
95  625  41.79
38  679  32.11
4   687  68.21
12  733   8.12
14  737  54.40
92  747  85.03
82  749  24.36
76  771  54.88
3   825   0.96
63  875  22.24
99  911  59.15
49  921  69.17
39  939  92.04

In [45]:
df2_098.sort_values(by='NILAI',ascending=False).head(15)

NIM  NILAI
90  247  98.25
40  313  95.55
39  939  92.04
92  747  85.03
34  491  84.95
57  291  82.39
19  131  79.97
66  363  70.59
16  123  69.76
49  921  69.17
4   687  68.21
94  529  66.82
60  619  65.23
37  477  61.23
24  201  61.06